version: "${VERSION}"

services:
  # Auth Service
  auth:
    build: ./auth
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"

  # Order Service
  order:
    build: ./order
    ports:
      - "${ORDER_PORT}:${ORDER_PORT}"
    depends_on:
      - rabbitmq
      - kafka
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - KAFKA_BROKER=${KAFKA_BROKER}

  # Payment Service
  payment:
    build: ./payment
    ports:
      - "${PAYMENT_PORT}:${PAYMENT_PORT}"
    depends_on:
      - rabbitmq
      - kafka
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - KAFKA_BROKER=${KAFKA_BROKER}

  # Notification Service
  notification:
    build: ./notification
    ports:
      - "${NOTIFICATION_PORT}:${NOTIFICATION_PORT}"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}

  # Product Service
  product:
    build: ./product
    ports:
      - "${PRODUCT_PORT}:${PRODUCT_PORT}"

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_UI_PORT}:${RABBITMQ_UI_PORT}"

  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"

  # Kafka
  kafka:
    image: wurstmeister/kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
    depends_on:
      - zookeeper
