version: "1.0"

services:
  # Auth Service
  auth:
    build: ./auth
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  # Order Service
  order:
    build: ./order
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
      - kafka
    environment:
      - PORT=5001
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - KAFKA_BROKER=kafka:9092

  # Payment Service
  payment:
    build: ./payment
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
      - kafka
    environment:
      - PORT=5002
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - KAFKA_BROKER=kafka:9092

  # Notification Service
  notification:
    build: ./notification
    ports:
      - "5003:5003"
    depends_on:
      - kafka
    environment:
      - PORT=5003
      - KAFKA_BROKER=kafka:9092

  # Product Service
  product:
    build: ./product
    ports:
      - "5004:5004"
    environment:
      - PORT=5004

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Main RabbitMQ port
      - "15672:15672" # UI Dashboard

  # Zookeeper (Kafka dependency)
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
