services:
  # Auth Service
  auth:
    build: ./auth
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    volumes:
      - ./auth:/app
    restart: always

  # Order Service
  order:
    build: ./order
    ports:
      - "${ORDER_PORT}:${ORDER_PORT}"
    depends_on:
      - rabbitmq
      - kafka
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - KAFKA_BROKER=${KAFKA_BROKER}
    volumes:
      - ./order:/app
    restart: always

  # Payment Service
  payment:
    build: ./payment
    ports:
      - "${PAYMENT_PORT}:${PAYMENT_PORT}"
    depends_on:
      - rabbitmq
      - kafka
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - KAFKA_BROKER=${KAFKA_BROKER}
    volumes:
      - ./payment:/app
    restart: always

  # Notification Service
  notification:
    build: ./notification
    ports:
      - "${NOTIFICATION_PORT}:${NOTIFICATION_PORT}"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
    volumes:
      - ./notification:/app
    restart: always

  # Product Service
  product:
    build: ./product
    ports:
      - "${PRODUCT_PORT}:${PRODUCT_PORT}"
    volumes:
      - ./product:/app
    restart: always

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_UI_PORT}:${RABBITMQ_UI_PORT}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # Zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  # Kafka
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:${KAFKA_PORT}
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  rabbitmq_data:
  zookeeper_data:
  kafka_data:
