version: "1.0"

services:
  # Auth Service
  auth:
    build: ./auth
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
      - kafka
    environment:
      - PORT=4000
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - KAFKA_BROKER=kafka:9092

  # Order Service
  order:
    build: ./order
    ports:
      - "4001:4001"
    depends_on:
      - rabbitmq
      - kafka
    environment:
      - PORT=4001
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - KAFKA_BROKER=kafka:9092

  # Payment Service
  payment:
    build: ./payment
    ports:
      - "4002:4002"
    depends_on:
      - rabbitmq
      - kafka
    environment:
      - PORT=4002
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - KAFKA_BROKER=kafka:9092

  # Notification Service
  notification:
    build: ./notification
    ports:
      - "4003:4003"
    depends_on:
      - kafka
    environment:
      - PORT=4003
      - KAFKA_BROKER=kafka:9092

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Main RabbitMQ port
      - "15672:15672" # UI Dashboard

  # Zookeeper (Kafka dependency)
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
